version: '3'

services:

  main:
    image: jenkinsci/jenkins:lts-alpine
    ports:
      - "50000:50000"
      - "8082:8080"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - ingress
    volumes:
      - main:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080

volumes:
  main:
    driver: local

networks:
  ingress:
    external: true

# docker service create --name jenkins \
#     -p 8082:8080 \
#     -p 50000:51000 \
#     -e JENKINS_OPTS="--prefix=/jenkins" \
#     --reserve-memory 300m \
#     --constraint "node.labels.build.role==master" \
#     --mount type=volume,volume-driver=local,source={{.Service.Name}}-{{.Task.Slot}}-vol,destination=/var/jenkins_home \
#     jenkinsci/jenkins:lts-alpine
